baseURL = "/"
title = "Jethro Kuan"
copyright = ""

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "Thoughts on software and life."
  dateFormat = "2006, Jan 2"
  copyrightOwner = "Jethro Kuan"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Jethro Kuan"

[author.social]
  # codepen = "JethroKuan"
  # facebook = "JethroKuan"
  github = "jethrokuan"
  # instagram = "instagram"
  # twitter = "MunifTanjim"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Github"
  weight = -70
  identifier = "github"
  url = "https://github.com/jethrokuan/"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
