baseURL = "/"
title = "How Things Work"
copyright = "Jethro Kuan"

theme = "minimo"

disqusShortname = ""
googleAnalytics = ""
Paginate = 5

preserveTaxonomyNames = true

[params]
  description = "A project by Jethro Kuan"
  dateFormat = "Jan 2, 2006"
  copyrightOwner = "Jethro Kuan"
  copyrightStartYear = "2017"
  favicon = "favicon.ico"
  hideEntryNavigation = false
  customCSS = ["css/custom.css"]
  customJS = ["js/custom.js"]

[params.seo]
  # Title Separator: - – — · • * ⋆ | ~ « » < >
  titleSeparator = "•"

[params.opengraph]
  [params.opengraph.facebook]
    admins = ""
    appid = ""

[taxonomies]
  category = "categories"
  tag = "tags"

[social]
  facebook = ""

[author]
  name = "Jethro Kuan"

# [author.social]
#   codepen = "MunifTanjim"
#   facebook = "MunifTanjim"
#   github = "MunifTanjim/minimo"
#   instagram = "instagram"
#   twitter = "MunifTanjim"

[permalinks]
  page = "/:slug/"

[[menu.main]]
  name = "Home"
  weight = 1
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 2
  identifier = "tags"
  url = "/tags/"

[[menu.main]]
  name = "Github"
  weight = 3
  identifier = "github"
  url = "https://github.com/jethrokuan/"

# Language Configuration
defaultContentLanguage = "en"

[languages]
  # edit this block for your own language
  [languages.en]
    lang = "en"
    languageName = "English"
    weight = 1
